language: generic
sudo: required
dist: trusty

env:
  - QGIS_REPO=http://qgis.org/debian-ltr
  - QGIS_REPO=http://qgis.org/debian
  - QGIS_REPO=http://qgis.org/debian-nightly

addons: 
  apt: 
    packages: 
      - python-software-properties 

-before_install:
  - sudo apt-get -qq -y update

install:
  - sudo add-apt-repository ${QGIS_REPO}
  - sudo apt-get update
  - sudo apt-get install -y --force-yes qgis python-qgis xvfb
  - sudo pip install --upgrade pip
  - sudo pip install coverage
  - sudo pip install nose
  - sudo pip install --upgrade pep8
  - sudo pip install --upgrade pylint
  - sudo pip install python-coveralls

before_script:
  - echo "Build starting on " `date`
  - export QGIS_PREFIX_PATH=/usr
  - export PYTHONPATH=${QGIS_PREFIX_PATH}/share/qgis/python/:${QGIS_PREFIX_PATH}/share/qgis/python/plugins:`pwd`
  - echo "PYTHONPATH:" $PYTHONPATH
  - export LD_LIBRARY_PATH=${QGIS_PREFIX_PATH}/lib

script:
  - pep8 --exclude=test ./
  - make pylint
  - QGIS_DEBUG=0 xvfb-run --server-args="-screen 0, 1024x768x24" nosetests -s --nologcapture -A 'not slow' -v --with-coverage --verbose --cover-package=qgis2web --cover-package=maindialog --cover-package=utils --cover-package=configparams --cover-package=olwriter --cover-package=leafletWriter  --cover-package=olScriptStrings --cover-package=basemaps --cover-package=leafletFileScripts --cover-package=leafletLayerScripts --cover-package=leafletScriptStrings --cover-package=leafletStyleScripts

after_success:
  - coveralls

notifications:
  email:
    - tom.chadwin@nnpa.org.uk
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5278d2ea8e892b8f3c32
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
