name: Run tests
on:
  pull_request:
    branches:
      - master
jobs:
  Test-Runner:
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      # - name: Install dependencies
      #   run: |
      #     sudo apt-get -y install docker-ce
      - name: Run test in Docker
        env:
          QGIS_TEST_VERSION: latest
          DISPLAY: 'var'
          QT_DEBUG_PLUGIN: 1
          QT_QPA_PLATFORM: offscreen
        run: |
          /usr/src/.docker/run-docker-tests.sh
      - run: echo "üçè This job's status is ${{ job.status }}."
